// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin/options/wgorm.proto

package wgorm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WGormFileOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WGormFileOptions) Reset()         { *m = WGormFileOptions{} }
func (m *WGormFileOptions) String() string { return proto.CompactTextString(m) }
func (*WGormFileOptions) ProtoMessage()    {}
func (*WGormFileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de170ddd6f8a2c1, []int{0}
}

func (m *WGormFileOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WGormFileOptions.Unmarshal(m, b)
}
func (m *WGormFileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WGormFileOptions.Marshal(b, m, deterministic)
}
func (m *WGormFileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WGormFileOptions.Merge(m, src)
}
func (m *WGormFileOptions) XXX_Size() int {
	return xxx_messageInfo_WGormFileOptions.Size(m)
}
func (m *WGormFileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WGormFileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WGormFileOptions proto.InternalMessageInfo

type WGormMessageOptions struct {
	Model                *bool    `protobuf:"varint,1,req,name=model" json:"model,omitempty"`
	Table                *string  `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
	Migrate              *bool    `protobuf:"varint,3,opt,name=migrate" json:"migrate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WGormMessageOptions) Reset()         { *m = WGormMessageOptions{} }
func (m *WGormMessageOptions) String() string { return proto.CompactTextString(m) }
func (*WGormMessageOptions) ProtoMessage()    {}
func (*WGormMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de170ddd6f8a2c1, []int{1}
}

func (m *WGormMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WGormMessageOptions.Unmarshal(m, b)
}
func (m *WGormMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WGormMessageOptions.Marshal(b, m, deterministic)
}
func (m *WGormMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WGormMessageOptions.Merge(m, src)
}
func (m *WGormMessageOptions) XXX_Size() int {
	return xxx_messageInfo_WGormMessageOptions.Size(m)
}
func (m *WGormMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WGormMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WGormMessageOptions proto.InternalMessageInfo

func (m *WGormMessageOptions) GetModel() bool {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return false
}

func (m *WGormMessageOptions) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *WGormMessageOptions) GetMigrate() bool {
	if m != nil && m.Migrate != nil {
		return *m.Migrate
	}
	return false
}

type WGormFieldOptions struct {
	Tag                  *WGormTag `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WGormFieldOptions) Reset()         { *m = WGormFieldOptions{} }
func (m *WGormFieldOptions) String() string { return proto.CompactTextString(m) }
func (*WGormFieldOptions) ProtoMessage()    {}
func (*WGormFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de170ddd6f8a2c1, []int{2}
}

func (m *WGormFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WGormFieldOptions.Unmarshal(m, b)
}
func (m *WGormFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WGormFieldOptions.Marshal(b, m, deterministic)
}
func (m *WGormFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WGormFieldOptions.Merge(m, src)
}
func (m *WGormFieldOptions) XXX_Size() int {
	return xxx_messageInfo_WGormFieldOptions.Size(m)
}
func (m *WGormFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WGormFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WGormFieldOptions proto.InternalMessageInfo

func (m *WGormFieldOptions) GetTag() *WGormTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type WGormTag struct {
	Gorm                 *string  `protobuf:"bytes,3,opt,name=gorm" json:"gorm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WGormTag) Reset()         { *m = WGormTag{} }
func (m *WGormTag) String() string { return proto.CompactTextString(m) }
func (*WGormTag) ProtoMessage()    {}
func (*WGormTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de170ddd6f8a2c1, []int{3}
}

func (m *WGormTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WGormTag.Unmarshal(m, b)
}
func (m *WGormTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WGormTag.Marshal(b, m, deterministic)
}
func (m *WGormTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WGormTag.Merge(m, src)
}
func (m *WGormTag) XXX_Size() int {
	return xxx_messageInfo_WGormTag.Size(m)
}
func (m *WGormTag) XXX_DiscardUnknown() {
	xxx_messageInfo_WGormTag.DiscardUnknown(m)
}

var xxx_messageInfo_WGormTag proto.InternalMessageInfo

func (m *WGormTag) GetGorm() string {
	if m != nil && m.Gorm != nil {
		return *m.Gorm
	}
	return ""
}

type AutoServerOptions struct {
	Autogen              *bool    `protobuf:"varint,1,opt,name=autogen" json:"autogen,omitempty"`
	TxnMiddleware        *bool    `protobuf:"varint,2,opt,name=txn_middleware,json=txnMiddleware" json:"txn_middleware,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoServerOptions) Reset()         { *m = AutoServerOptions{} }
func (m *AutoServerOptions) String() string { return proto.CompactTextString(m) }
func (*AutoServerOptions) ProtoMessage()    {}
func (*AutoServerOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de170ddd6f8a2c1, []int{4}
}

func (m *AutoServerOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoServerOptions.Unmarshal(m, b)
}
func (m *AutoServerOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoServerOptions.Marshal(b, m, deterministic)
}
func (m *AutoServerOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoServerOptions.Merge(m, src)
}
func (m *AutoServerOptions) XXX_Size() int {
	return xxx_messageInfo_AutoServerOptions.Size(m)
}
func (m *AutoServerOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoServerOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AutoServerOptions proto.InternalMessageInfo

func (m *AutoServerOptions) GetAutogen() bool {
	if m != nil && m.Autogen != nil {
		return *m.Autogen
	}
	return false
}

func (m *AutoServerOptions) GetTxnMiddleware() bool {
	if m != nil && m.TxnMiddleware != nil {
		return *m.TxnMiddleware
	}
	return false
}

type MethodOptions struct {
	ObjectType           *string  `protobuf:"bytes,1,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de170ddd6f8a2c1, []int{5}
}

func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

func (m *MethodOptions) GetObjectType() string {
	if m != nil && m.ObjectType != nil {
		return *m.ObjectType
	}
	return ""
}

var E_FileOpts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*WGormFileOptions)(nil),
	Field:         99432,
	Name:          "wgorm.file_opts",
	Tag:           "bytes,99432,opt,name=file_opts",
	Filename:      "plugin/options/wgorm.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*WGormMessageOptions)(nil),
	Field:         99432,
	Name:          "wgorm.opts",
	Tag:           "bytes,99432,opt,name=opts",
	Filename:      "plugin/options/wgorm.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*WGormFieldOptions)(nil),
	Field:         99432,
	Name:          "wgorm.field",
	Tag:           "bytes,99432,opt,name=field",
	Filename:      "plugin/options/wgorm.proto",
}

var E_Server = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*AutoServerOptions)(nil),
	Field:         99432,
	Name:          "wgorm.server",
	Tag:           "bytes,99432,opt,name=server",
	Filename:      "plugin/options/wgorm.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         99432,
	Name:          "wgorm.method",
	Tag:           "bytes,99432,opt,name=method",
	Filename:      "plugin/options/wgorm.proto",
}

func init() {
	proto.RegisterType((*WGormFileOptions)(nil), "wgorm.WGormFileOptions")
	proto.RegisterType((*WGormMessageOptions)(nil), "wgorm.WGormMessageOptions")
	proto.RegisterType((*WGormFieldOptions)(nil), "wgorm.WGormFieldOptions")
	proto.RegisterType((*WGormTag)(nil), "wgorm.WGormTag")
	proto.RegisterType((*AutoServerOptions)(nil), "wgorm.AutoServerOptions")
	proto.RegisterType((*MethodOptions)(nil), "wgorm.MethodOptions")
	proto.RegisterExtension(E_FileOpts)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Server)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("plugin/options/wgorm.proto", fileDescriptor_8de170ddd6f8a2c1) }

var fileDescriptor_8de170ddd6f8a2c1 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x6f, 0xd4, 0x30,
	0x10, 0x85, 0x95, 0xb6, 0xbb, 0xcd, 0x4e, 0x55, 0xa0, 0xa6, 0x12, 0xd6, 0x0a, 0xda, 0x10, 0x09,
	0x69, 0x4f, 0x59, 0xc4, 0x81, 0x43, 0x6e, 0x5c, 0xe0, 0xb4, 0x54, 0xb8, 0x91, 0x38, 0x70, 0x58,
	0x65, 0x37, 0x13, 0x63, 0xe4, 0xc4, 0x91, 0xe3, 0xd0, 0xf6, 0x1f, 0xf0, 0x53, 0xf9, 0x19, 0x28,
	0x76, 0x92, 0x26, 0xea, 0x72, 0xcb, 0x7b, 0x7e, 0xfa, 0x32, 0x33, 0x0f, 0x96, 0x95, 0x6c, 0xb8,
	0x28, 0xd7, 0xaa, 0x32, 0x42, 0x95, 0xf5, 0xfa, 0x8e, 0x2b, 0x5d, 0x44, 0x95, 0x56, 0x46, 0x91,
	0x99, 0x15, 0xcb, 0x80, 0x2b, 0xc5, 0x25, 0xae, 0xad, 0xb9, 0x6b, 0xf2, 0x75, 0x86, 0xf5, 0x5e,
	0x8b, 0xca, 0x28, 0xed, 0x82, 0x21, 0x81, 0x17, 0xdf, 0xbf, 0x28, 0x5d, 0x7c, 0x16, 0x12, 0x6f,
	0x1c, 0x28, 0xfc, 0x01, 0x2f, 0xad, 0xb7, 0xc1, 0xba, 0x4e, 0x79, 0x6f, 0x93, 0x4b, 0x98, 0x15,
	0x2a, 0x43, 0x49, 0xbd, 0xe0, 0x68, 0xe5, 0x33, 0x27, 0x5a, 0xd7, 0xa4, 0x3b, 0x89, 0xf4, 0x28,
	0xf0, 0x56, 0x0b, 0xe6, 0x04, 0xa1, 0x70, 0x5a, 0x08, 0xae, 0x53, 0x83, 0xf4, 0x38, 0xf0, 0x56,
	0x3e, 0xeb, 0x65, 0xf8, 0x11, 0x2e, 0xba, 0x1f, 0xa2, 0xcc, 0x7a, 0xf4, 0x5b, 0x38, 0x36, 0x29,
	0xa7, 0x5e, 0xe0, 0xad, 0xce, 0x3e, 0x3c, 0x8f, 0xdc, 0x26, 0x36, 0x96, 0xa4, 0x9c, 0xb5, 0x6f,
	0xe1, 0x15, 0xf8, 0xbd, 0x41, 0x08, 0x9c, 0xb4, 0x09, 0x8b, 0x5e, 0x30, 0xfb, 0x1d, 0x26, 0x70,
	0xf1, 0xa9, 0x31, 0xea, 0x16, 0xf5, 0x6f, 0xd4, 0x3d, 0x97, 0xc2, 0x69, 0xda, 0x18, 0xc5, 0xb1,
	0xb4, 0x6c, 0x9f, 0xf5, 0x92, 0xbc, 0x83, 0x67, 0xe6, 0xbe, 0xdc, 0x16, 0x22, 0xcb, 0x24, 0xde,
	0xa5, 0xda, 0xcd, 0xef, 0xb3, 0x73, 0x73, 0x5f, 0x6e, 0x06, 0x33, 0x7c, 0x0f, 0xe7, 0x1b, 0x34,
	0x3f, 0xd5, 0x30, 0xe9, 0x35, 0x9c, 0xa9, 0xdd, 0x2f, 0xdc, 0x9b, 0xad, 0x79, 0xa8, 0xd0, 0x52,
	0x17, 0x0c, 0x9c, 0x95, 0x3c, 0x54, 0x18, 0x27, 0xb0, 0xc8, 0x85, 0xc4, 0xad, 0xaa, 0x4c, 0x4d,
	0x5e, 0x47, 0xae, 0x80, 0xa8, 0x2f, 0x20, 0x1a, 0xdd, 0x99, 0xfe, 0xfd, 0x33, 0xb7, 0x0b, 0xbf,
	0x1a, 0x2f, 0x3c, 0x0a, 0x30, 0x3f, 0x77, 0xa2, 0x8e, 0xbf, 0xc1, 0x89, 0x05, 0x5e, 0x3f, 0x01,
	0x4e, 0x4b, 0x1a, 0x98, 0xcb, 0x31, 0x73, 0x9a, 0x61, 0x16, 0x15, 0xdf, 0xc0, 0x2c, 0x6f, 0x3b,
	0x20, 0x6f, 0x0e, 0x0c, 0xf9, 0xd8, 0xcd, 0x40, 0xa4, 0xd3, 0x29, 0x1f, 0x13, 0xcc, 0x71, 0xe2,
	0x5b, 0x98, 0xd7, 0xf6, 0xfa, 0x07, 0xa6, 0x6c, 0x6b, 0x11, 0x7b, 0xfc, 0x1f, 0xf3, 0x49, 0x73,
	0xac, 0x43, 0xc5, 0x5f, 0x61, 0x5e, 0xd8, 0x02, 0xc8, 0xd5, 0x81, 0xd5, 0x47, 0xcd, 0x0c, 0xcc,
	0xcb, 0x8e, 0x39, 0x79, 0x65, 0x1d, 0xe5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xfb, 0x07,
	0xa3, 0x35, 0x03, 0x00, 0x00,
}
