// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin/options/worm.proto

package worm

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type WormFileOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WormFileOptions) Reset()         { *m = WormFileOptions{} }
func (m *WormFileOptions) String() string { return proto.CompactTextString(m) }
func (*WormFileOptions) ProtoMessage()    {}
func (*WormFileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c056d40fbc59afe5, []int{0}
}

func (m *WormFileOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WormFileOptions.Unmarshal(m, b)
}
func (m *WormFileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WormFileOptions.Marshal(b, m, deterministic)
}
func (m *WormFileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WormFileOptions.Merge(m, src)
}
func (m *WormFileOptions) XXX_Size() int {
	return xxx_messageInfo_WormFileOptions.Size(m)
}
func (m *WormFileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WormFileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WormFileOptions proto.InternalMessageInfo

type WormMessageOptions struct {
	Model                *bool    `protobuf:"varint,1,req,name=model" json:"model,omitempty"`
	Table                *string  `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
	Merge                *string  `protobuf:"bytes,4,opt,name=merge" json:"merge,omitempty"`
	Migrate              *bool    `protobuf:"varint,3,opt,name=migrate" json:"migrate,omitempty"`
	ConvertTo            *string  `protobuf:"bytes,5,opt,name=convertTo" json:"convertTo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WormMessageOptions) Reset()         { *m = WormMessageOptions{} }
func (m *WormMessageOptions) String() string { return proto.CompactTextString(m) }
func (*WormMessageOptions) ProtoMessage()    {}
func (*WormMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c056d40fbc59afe5, []int{1}
}

func (m *WormMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WormMessageOptions.Unmarshal(m, b)
}
func (m *WormMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WormMessageOptions.Marshal(b, m, deterministic)
}
func (m *WormMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WormMessageOptions.Merge(m, src)
}
func (m *WormMessageOptions) XXX_Size() int {
	return xxx_messageInfo_WormMessageOptions.Size(m)
}
func (m *WormMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WormMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WormMessageOptions proto.InternalMessageInfo

func (m *WormMessageOptions) GetModel() bool {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return false
}

func (m *WormMessageOptions) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *WormMessageOptions) GetMerge() string {
	if m != nil && m.Merge != nil {
		return *m.Merge
	}
	return ""
}

func (m *WormMessageOptions) GetMigrate() bool {
	if m != nil && m.Migrate != nil {
		return *m.Migrate
	}
	return false
}

func (m *WormMessageOptions) GetConvertTo() string {
	if m != nil && m.ConvertTo != nil {
		return *m.ConvertTo
	}
	return ""
}

type WormFieldOptions struct {
	Tag                  *WormTag `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WormFieldOptions) Reset()         { *m = WormFieldOptions{} }
func (m *WormFieldOptions) String() string { return proto.CompactTextString(m) }
func (*WormFieldOptions) ProtoMessage()    {}
func (*WormFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c056d40fbc59afe5, []int{2}
}

func (m *WormFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WormFieldOptions.Unmarshal(m, b)
}
func (m *WormFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WormFieldOptions.Marshal(b, m, deterministic)
}
func (m *WormFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WormFieldOptions.Merge(m, src)
}
func (m *WormFieldOptions) XXX_Size() int {
	return xxx_messageInfo_WormFieldOptions.Size(m)
}
func (m *WormFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WormFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WormFieldOptions proto.InternalMessageInfo

func (m *WormFieldOptions) GetTag() *WormTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type WormTag struct {
	Gorm                 *string  `protobuf:"bytes,3,opt,name=gorm" json:"gorm,omitempty"`
	Validator            *string  `protobuf:"bytes,4,opt,name=validator" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WormTag) Reset()         { *m = WormTag{} }
func (m *WormTag) String() string { return proto.CompactTextString(m) }
func (*WormTag) ProtoMessage()    {}
func (*WormTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_c056d40fbc59afe5, []int{3}
}

func (m *WormTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WormTag.Unmarshal(m, b)
}
func (m *WormTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WormTag.Marshal(b, m, deterministic)
}
func (m *WormTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WormTag.Merge(m, src)
}
func (m *WormTag) XXX_Size() int {
	return xxx_messageInfo_WormTag.Size(m)
}
func (m *WormTag) XXX_DiscardUnknown() {
	xxx_messageInfo_WormTag.DiscardUnknown(m)
}

var xxx_messageInfo_WormTag proto.InternalMessageInfo

func (m *WormTag) GetGorm() string {
	if m != nil && m.Gorm != nil {
		return *m.Gorm
	}
	return ""
}

func (m *WormTag) GetValidator() string {
	if m != nil && m.Validator != nil {
		return *m.Validator
	}
	return ""
}

type Pagination struct {
	TotalCount           *int32   `protobuf:"varint,1,req,name=totalCount" json:"totalCount,omitempty"`
	TotalPages           *int32   `protobuf:"varint,2,req,name=totalPages" json:"totalPages,omitempty"`
	CurrentPage          *int32   `protobuf:"varint,3,req,name=currentPage" json:"currentPage,omitempty"`
	Size                 *int32   `protobuf:"varint,4,req,name=size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_c056d40fbc59afe5, []int{4}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetTotalCount() int32 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

func (m *Pagination) GetTotalPages() int32 {
	if m != nil && m.TotalPages != nil {
		return *m.TotalPages
	}
	return 0
}

func (m *Pagination) GetCurrentPage() int32 {
	if m != nil && m.CurrentPage != nil {
		return *m.CurrentPage
	}
	return 0
}

func (m *Pagination) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

type AutoServerOptions struct {
	Autogen              *bool    `protobuf:"varint,1,opt,name=autogen" json:"autogen,omitempty"`
	TxnMiddleware        *bool    `protobuf:"varint,2,opt,name=txn_middleware,json=txnMiddleware" json:"txn_middleware,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoServerOptions) Reset()         { *m = AutoServerOptions{} }
func (m *AutoServerOptions) String() string { return proto.CompactTextString(m) }
func (*AutoServerOptions) ProtoMessage()    {}
func (*AutoServerOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c056d40fbc59afe5, []int{5}
}

func (m *AutoServerOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoServerOptions.Unmarshal(m, b)
}
func (m *AutoServerOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoServerOptions.Marshal(b, m, deterministic)
}
func (m *AutoServerOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoServerOptions.Merge(m, src)
}
func (m *AutoServerOptions) XXX_Size() int {
	return xxx_messageInfo_AutoServerOptions.Size(m)
}
func (m *AutoServerOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoServerOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AutoServerOptions proto.InternalMessageInfo

func (m *AutoServerOptions) GetAutogen() bool {
	if m != nil && m.Autogen != nil {
		return *m.Autogen
	}
	return false
}

func (m *AutoServerOptions) GetTxnMiddleware() bool {
	if m != nil && m.TxnMiddleware != nil {
		return *m.TxnMiddleware
	}
	return false
}

type MethodOptions struct {
	ObjectType           *string  `protobuf:"bytes,1,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c056d40fbc59afe5, []int{6}
}

func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

func (m *MethodOptions) GetObjectType() string {
	if m != nil && m.ObjectType != nil {
		return *m.ObjectType
	}
	return ""
}

var E_FileOpts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*WormFileOptions)(nil),
	Field:         99432,
	Name:          "worm.file_opts",
	Tag:           "bytes,99432,opt,name=file_opts",
	Filename:      "plugin/options/worm.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*WormMessageOptions)(nil),
	Field:         99432,
	Name:          "worm.opts",
	Tag:           "bytes,99432,opt,name=opts",
	Filename:      "plugin/options/worm.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*WormFieldOptions)(nil),
	Field:         99432,
	Name:          "worm.field",
	Tag:           "bytes,99432,opt,name=field",
	Filename:      "plugin/options/worm.proto",
}

var E_Server = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*AutoServerOptions)(nil),
	Field:         99432,
	Name:          "worm.server",
	Tag:           "bytes,99432,opt,name=server",
	Filename:      "plugin/options/worm.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         99432,
	Name:          "worm.method",
	Tag:           "bytes,99432,opt,name=method",
	Filename:      "plugin/options/worm.proto",
}

func init() {
	proto.RegisterType((*WormFileOptions)(nil), "worm.WormFileOptions")
	proto.RegisterType((*WormMessageOptions)(nil), "worm.WormMessageOptions")
	proto.RegisterType((*WormFieldOptions)(nil), "worm.WormFieldOptions")
	proto.RegisterType((*WormTag)(nil), "worm.WormTag")
	proto.RegisterType((*Pagination)(nil), "worm.Pagination")
	proto.RegisterType((*AutoServerOptions)(nil), "worm.AutoServerOptions")
	proto.RegisterType((*MethodOptions)(nil), "worm.MethodOptions")
	proto.RegisterExtension(E_FileOpts)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Server)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("plugin/options/worm.proto", fileDescriptor_c056d40fbc59afe5) }

var fileDescriptor_c056d40fbc59afe5 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x14, 0x54, 0xfa, 0xdd, 0x57, 0x15, 0x58, 0xf3, 0x65, 0xd0, 0xb2, 0x1b, 0x45, 0x42, 0xea, 0xa9,
	0x45, 0x70, 0x2b, 0x27, 0x84, 0xc4, 0xad, 0xda, 0x95, 0xa9, 0xc4, 0xb1, 0x72, 0x9b, 0x57, 0x63,
	0x94, 0xc4, 0x91, 0xe3, 0x74, 0x77, 0x39, 0x72, 0xe2, 0xc4, 0xef, 0xe4, 0x67, 0xac, 0x6c, 0x37,
	0x4d, 0xaa, 0xf6, 0x96, 0x99, 0x79, 0x19, 0xcf, 0xfb, 0x80, 0x37, 0x79, 0x52, 0x0a, 0x99, 0xcd,
	0x54, 0x6e, 0xa4, 0xca, 0x8a, 0xd9, 0x9d, 0xd2, 0xe9, 0x34, 0xd7, 0xca, 0x28, 0xd2, 0xb1, 0xdf,
	0x6f, 0x43, 0xa1, 0x94, 0x48, 0x70, 0xe6, 0xb8, 0x75, 0xb9, 0x9d, 0xc5, 0x58, 0x6c, 0xb4, 0xcc,
	0x8d, 0xd2, 0xbe, 0x2e, 0xba, 0x80, 0xa7, 0x3f, 0x94, 0x4e, 0xbf, 0xc9, 0x04, 0x6f, 0xbc, 0x4b,
	0xf4, 0x2f, 0x00, 0x62, 0xb9, 0x05, 0x16, 0x05, 0x17, 0x15, 0x4d, 0x5e, 0x40, 0x37, 0x55, 0x31,
	0x26, 0x34, 0x08, 0x5b, 0x93, 0x01, 0xf3, 0xc0, 0xb2, 0x86, 0xaf, 0x13, 0xa4, 0xad, 0x30, 0x98,
	0x0c, 0x99, 0x07, 0xae, 0x16, 0xb5, 0x40, 0xda, 0xf1, 0xac, 0x03, 0x84, 0x42, 0x3f, 0x95, 0x42,
	0x73, 0x83, 0xb4, 0x1d, 0x06, 0x93, 0x01, 0xab, 0x20, 0xb9, 0x84, 0xe1, 0x46, 0x65, 0x3b, 0xd4,
	0x66, 0xa9, 0x68, 0xd7, 0xfd, 0x53, 0x13, 0xd1, 0x27, 0x78, 0xe6, 0x33, 0x62, 0x12, 0x57, 0x69,
	0xae, 0xa1, 0x6d, 0xb8, 0xa0, 0x41, 0x18, 0x4c, 0x46, 0x1f, 0xc7, 0x53, 0xd7, 0xb9, 0x2d, 0x5a,
	0x72, 0xc1, 0xac, 0x12, 0x7d, 0x86, 0xfe, 0x1e, 0x13, 0x02, 0x1d, 0xa1, 0x74, 0xea, 0x1e, 0x1d,
	0x32, 0xf7, 0x6d, 0x5f, 0xdc, 0xf1, 0x44, 0xc6, 0xdc, 0x28, 0xbd, 0x4f, 0x59, 0x13, 0xd1, 0x9f,
	0x00, 0xe0, 0x96, 0x0b, 0x99, 0x71, 0xfb, 0x1a, 0xb9, 0x02, 0x30, 0xca, 0xf0, 0xe4, 0xab, 0x2a,
	0x33, 0xe3, 0xfa, 0xef, 0xb2, 0x06, 0x73, 0xd0, 0x6f, 0xb9, 0xc0, 0x82, 0xb6, 0x1a, 0xba, 0x63,
	0x48, 0x08, 0xa3, 0x4d, 0xa9, 0x35, 0x66, 0xc6, 0x62, 0xda, 0x76, 0x05, 0x4d, 0xca, 0x46, 0x2c,
	0xe4, 0x6f, 0x3b, 0x2f, 0x2b, 0xb9, 0xef, 0x68, 0x09, 0x17, 0x5f, 0x4a, 0xa3, 0xbe, 0xa3, 0xde,
	0xa1, 0xae, 0xfa, 0xa6, 0xd0, 0xe7, 0xa5, 0x51, 0x02, 0x33, 0xd7, 0xfb, 0x80, 0x55, 0x90, 0xbc,
	0x87, 0x27, 0xe6, 0x3e, 0x5b, 0xa5, 0x32, 0x8e, 0x13, 0xbc, 0xe3, 0xda, 0xaf, 0x64, 0xc0, 0xc6,
	0xe6, 0x3e, 0x5b, 0x1c, 0xc8, 0xe8, 0x03, 0x8c, 0x17, 0x68, 0x7e, 0xaa, 0xc6, 0x24, 0x47, 0x6a,
	0xfd, 0x0b, 0x37, 0x66, 0x65, 0x1e, 0x72, 0x74, 0xae, 0x43, 0x06, 0x9e, 0x5a, 0x3e, 0xe4, 0x38,
	0x67, 0x30, 0xdc, 0xca, 0x04, 0x57, 0x2a, 0x37, 0x05, 0xb9, 0x9c, 0xfa, 0x93, 0x9a, 0x56, 0x27,
	0x35, 0x6d, 0x9c, 0x0e, 0xfd, 0xff, 0xb7, 0xe7, 0x16, 0xf2, 0xb2, 0x5e, 0x48, 0x43, 0x66, 0x83,
	0xad, 0x07, 0xc5, 0xfc, 0x06, 0x3a, 0xce, 0xee, 0xfa, 0xc4, 0xee, 0xf8, 0xea, 0x0e, 0x8e, 0xb4,
	0x76, 0x3c, 0xae, 0x60, 0xce, 0x68, 0xbe, 0x80, 0xee, 0xd6, 0xde, 0x07, 0x79, 0x77, 0x26, 0x60,
	0x7d, 0x37, 0x07, 0xbf, 0x57, 0xcd, 0x84, 0xb5, 0xce, 0xbc, 0xcb, 0x9c, 0x41, 0xaf, 0x70, 0x73,
	0x3f, 0x93, 0xd0, 0x2e, 0x44, 0x6e, 0x4e, 0x12, 0xbe, 0xf6, 0x8e, 0x27, 0x2b, 0x63, 0x7b, 0xa7,
	0xf9, 0x02, 0x7a, 0xa9, 0x9b, 0x3c, 0xb9, 0x3a, 0xd3, 0x75, 0x63, 0x25, 0x07, 0xcb, 0xe7, 0xde,
	0xf2, 0x48, 0x64, 0x7b, 0x93, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xfb, 0xa0, 0xe2, 0xfd,
	0x03, 0x00, 0x00,
}
